import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

// Next's shareable config is still eslintrc-shaped, so it is bridged into flat
// config rather than duplicated by hand.
const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  // next-env.d.ts is generated by Next on every build; linting it is noise.
  { ignores: ['.next/**', 'next-env.d.ts', 'node_modules/**', 'playwright-report/**', 'test-results/**'] },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
];

export default config;
